# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [81]:
import numpy as np

#### Create an array of 10 zeros 

In [82]:
import numpy as np
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [83]:
import numpy as np
array=np.ones(10)
print(array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [84]:
import numpy as np
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [85]:
import numpy as np
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [86]:
import numpy as np
array=np.arange(10,51,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [87]:
import numpy as np
x =  np.arange(0, 8).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#### Create a 3x3 identity matrix

In [88]:
import numpy as np
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [89]:
import numpy as np
randnum = np.random.normal(0,1,1)
print(randnum)

[-0.58679563]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [90]:
import numpy as np
rand = np.random.normal(0,1,25)
print(rand)

[ 0.19396371 -1.26586862  2.17060938 -0.81326926  0.95046791  1.22819014
  1.69839495 -1.49937476  0.62439405 -1.23598098 -0.19521864  0.27685106
 -0.58951974 -0.56584486 -0.09646985 -0.01346445  0.29913477 -0.13365427
 -1.15505659  2.08394415  1.12014857  1.36196794  0.79037324  0.47230941
  0.15480038]


#### Create the following matrix:

In [91]:
import numpy as np
array=np.arange(10,50,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [92]:
num_line = np.linspace(0,1,20)

print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [93]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [94]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [95]:
ar = mat[2:5, 1:5]
print(ar)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [96]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [97]:
num=mat[3,4]
print(num)

20


In [98]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [99]:
num=mat[0][1]
num1=mat[1][1]
num2=mat[2][1]
print(num)
print(num1)
print(num2)

2
7
12


In [100]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [101]:
row = mat[4]
print(row)

[21 22 23 24 25]


In [102]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [103]:
rows = mat[3:5, :]
print(rows)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [104]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [105]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [106]:

Array = np.array(mat)
print(np.sum(Array, axis = 0))

[55 60 65 70 75]
